const LOGO_DATA = [
  { year: 1966, event_type: "Super Bowl", label: "Super Bowl I", url: "logos/super-bowl-1966.gif" },
  { year: 1967, event_type: "Super Bowl", label: "Super Bowl II", url: "logos/super-bowl-1967.gif" },
  { year: 1968, event_type: "Super Bowl", label: "Super Bowl III", url: "logos/super-bowl-1968.gif" },
  { year: 1969, event_type: "Super Bowl", label: "Super Bowl IV", url: "logos/super-bowl-1969.gif" },
  { year: 1970, event_type: "Super Bowl", label: "Super Bowl V", url: "logos/super-bowl-1970.gif" },
  { year: 1971, event_type: "Super Bowl", label: "Super Bowl VI", url: "logos/super-bowl-1971.gif" },
  { year: 1972, event_type: "Super Bowl", label: "Super Bowl VII", url: "logos/super-bowl-1972.gif" },
  { year: 1973, event_type: "Super Bowl", label: "Super Bowl VIII", url: "logos/super-bowl-1973.gif" },
  { year: 1974, event_type: "Super Bowl", label: "Super Bowl IX", url: "logos/super-bowl-1974.gif" },
  { year: 1975, event_type: "Super Bowl", label: "Super Bowl X", url: "logos/super-bowl-1975.gif" },
  { year: 1976, event_type: "Super Bowl", label: "Super Bowl XI", url: "logos/super-bowl-1976.gif" },
  { year: 1977, event_type: "Super Bowl", label: "Super Bowl XII", url: "logos/super-bowl-1977.gif" },
  { year: 1978, event_type: "Super Bowl", label: "Super Bowl XIII", url: "logos/super-bowl-1978.gif" },
  { year: 1979, event_type: "Super Bowl", label: "Super Bowl XIV", url: "logos/super-bowl-1979.gif" },
  { year: 1980, event_type: "Super Bowl", label: "Super Bowl XV", url: "logos/super-bowl-1980.gif" },
  { year: 1981, event_type: "Super Bowl", label: "Super Bowl XVI", url: "logos/super-bowl-1981.gif" },
  { year: 1982, event_type: "Super Bowl", label: "Super Bowl XVII", url: "logos/super-bowl-1982.gif" },
  { year: 1983, event_type: "Super Bowl", label: "Super Bowl XVIII", url: "logos/super-bowl-1983.gif" },
  { year: 1984, event_type: "Super Bowl", label: "Super Bowl XIX", url: "logos/super-bowl-1984.gif" },
  { year: 1985, event_type: "Super Bowl", label: "Super Bowl XX", url: "logos/super-bowl-1985.gif" },
  { year: 1986, event_type: "Super Bowl", label: "Super Bowl XXI", url: "logos/super-bowl-1986.gif" },
  { year: 1987, event_type: "Super Bowl", label: "Super Bowl XXII", url: "logos/super-bowl-1987.gif" },
  { year: 1988, event_type: "Super Bowl", label: "Super Bowl XXIII", url: "logos/super-bowl-1988.gif" },
  { year: 1989, event_type: "Super Bowl", label: "Super Bowl XXIV", url: "logos/super-bowl-1989.gif" },
  { year: 1990, event_type: "Super Bowl", label: "Super Bowl XXV", url: "logos/super-bowl-1990.gif" },
  { year: 1991, event_type: "Super Bowl", label: "Super Bowl XXVI", url: "logos/super-bowl-1991.gif" },
  { year: 1992, event_type: "Super Bowl", label: "Super Bowl XXVII", url: "logos/super-bowl-1992.gif" },
  { year: 1993, event_type: "Super Bowl", label: "Super Bowl XXVIII", url: "logos/super-bowl-1993.gif" },
  { year: 1994, event_type: "Super Bowl", label: "Super Bowl XXIX", url: "logos/super-bowl-1994.gif" },
  { year: 1995, event_type: "Super Bowl", label: "Super Bowl XXX", url: "logos/super-bowl-1995.gif" },
  { year: 1996, event_type: "Super Bowl", label: "Super Bowl XXXI", url: "logos/super-bowl-1996.gif" },
  { year: 1997, event_type: "Super Bowl", label: "Super Bowl XXXII", url: "logos/super-bowl-1997.gif" },
  { year: 1998, event_type: "Super Bowl", label: "Super Bowl XXXIII", url: "logos/super-bowl-1998.gif" },
  { year: 1999, event_type: "Super Bowl", label: "Super Bowl XXXIV", url: "logos/super-bowl-1999.gif" },
  { year: 2000, event_type: "Super Bowl", label: "Super Bowl XXXV", url: "logos/super-bowl-2000.gif" },
  { year: 2001, event_type: "Super Bowl", label: "Super Bowl XXXVI", url: "logos/super-bowl-2001.gif" },
  { year: 2002, event_type: "Super Bowl", label: "Super Bowl XXXVII", url: "logos/super-bowl-2002.gif" },
  { year: 2003, event_type: "Super Bowl", label: "Super Bowl XXXVIII", url: "logos/super-bowl-2003.gif" },
  { year: 2004, event_type: "Super Bowl", label: "Super Bowl XXXIX", url: "logos/super-bowl-2004.gif" },
  { year: 2005, event_type: "Super Bowl", label: "Super Bowl XL", url: "logos/super-bowl-2005.gif" },
  { year: 2006, event_type: "Super Bowl", label: "Super Bowl XLI", url: "logos/super-bowl-2006.gif" },
  { year: 2007, event_type: "Super Bowl", label: "Super Bowl XLII", url: "logos/super-bowl-2007.gif" },
  { year: 2008, event_type: "Super Bowl", label: "Super Bowl XLIII", url: "logos/super-bowl-2008.gif" },
  { year: 2009, event_type: "Super Bowl", label: "Super Bowl XLIV", url: "logos/super-bowl-2009.gif" },
  { year: 2010, event_type: "Super Bowl", label: "Super Bowl XLV", url: "logos/super-bowl-2010.gif" },
  { year: 2011, event_type: "Super Bowl", label: "Super Bowl XLVI", url: "logos/super-bowl-2011.gif" },
  { year: 2012, event_type: "Super Bowl", label: "Super Bowl XLVII", url: "logos/super-bowl-2012.gif" },
  { year: 2013, event_type: "Super Bowl", label: "Super Bowl XLVIII", url: "logos/super-bowl-2013.gif" },
  { year: 2014, event_type: "Super Bowl", label: "Super Bowl XLIX", url: "logos/super-bowl-2014.gif" },
  { year: 2015, event_type: "Super Bowl", label: "Super Bowl 50", url: "logos/super-bowl-2015.gif" },
  { year: 2016, event_type: "Super Bowl", label: "Super Bowl LI", url: "logos/super-bowl-2016.gif" },
  { year: 2017, event_type: "Super Bowl", label: "Super Bowl LII", url: "logos/super-bowl-2017.gif" },
  { year: 2018, event_type: "Super Bowl", label: "Super Bowl LIII", url: "logos/super-bowl-2018.gif" },
  { year: 2019, event_type: "Super Bowl", label: "Super Bowl LIV", url: "logos/super-bowl-2019.gif" },
  { year: 2020, event_type: "Super Bowl", label: "Super Bowl LV", url: "logos/super-bowl-2020.gif" },
  { year: 2021, event_type: "Super Bowl", label: "Super Bowl LVI", url: "logos/super-bowl-2021.gif" },
  { year: 2022, event_type: "Super Bowl", label: "Super Bowl LVII", url: "logos/super-bowl-2022.gif" },
  { year: 2023, event_type: "Super Bowl", label: "Super Bowl LVIII", url: "logos/super-bowl-2023.gif" },
  { year: 2024, event_type: "Super Bowl", label: "Super Bowl LIX", url: "logos/super-bowl-2024.gif" },
  { year: 2025, event_type: "Super Bowl", label: "Super Bowl LX", url: "logos/super-bowl-2025.gif" },
  { year: 2026, event_type: "Super Bowl", label: "Super Bowl LXI", url: "logos/super-bowl-2026.png" },
  { year: 1930, event_type: "World Cup", label: "World Cup 1930", url: "logos/world-cup-1930.gif" },
  { year: 1934, event_type: "World Cup", label: "World Cup 1934", url: "logos/world-cup-1934.gif" },
  { year: 1938, event_type: "World Cup", label: "World Cup 1938", url: "logos/world-cup-1938.gif" },
  { year: 1950, event_type: "World Cup", label: "World Cup 1950", url: "logos/world-cup-1950.gif" },
  { year: 1954, event_type: "World Cup", label: "World Cup 1954", url: "logos/world-cup-1954.gif" },
  { year: 1958, event_type: "World Cup", label: "World Cup 1958", url: "logos/world-cup-1958.gif" },
  { year: 1962, event_type: "World Cup", label: "World Cup 1962", url: "logos/world-cup-1962.gif" },
  { year: 1966, event_type: "World Cup", label: "World Cup 1966", url: "logos/world-cup-1966.gif" },
  { year: 1970, event_type: "World Cup", label: "World Cup 1970", url: "logos/world-cup-1970.png" },
  { year: 1974, event_type: "World Cup", label: "World Cup 1974", url: "logos/world-cup-1974.png" },
  { year: 1978, event_type: "World Cup", label: "World Cup 1978", url: "logos/world-cup-1978.png" },
  { year: 1982, event_type: "World Cup", label: "World Cup 1982", url: "logos/world-cup-1982.png" },
  { year: 1986, event_type: "World Cup", label: "World Cup 1986", url: "logos/world-cup-1986.gif" },
  { year: 1990, event_type: "World Cup", label: "World Cup 1990", url: "logos/world-cup-1990.png" },
  { year: 1994, event_type: "World Cup", label: "World Cup 1994", url: "logos/world-cup-1994.png" },
  { year: 1998, event_type: "World Cup", label: "World Cup 1998", url: "logos/world-cup-1998.gif" },
  { year: 2002, event_type: "World Cup", label: "World Cup 2002", url: "logos/world-cup-2002.gif" },
  { year: 2006, event_type: "World Cup", label: "World Cup 2006", url: "logos/world-cup-2006.gif" },
  { year: 2010, event_type: "World Cup", label: "World Cup 2010", url: "logos/world-cup-2010.gif" },
  { year: 2014, event_type: "World Cup", label: "World Cup 2014", url: "logos/world-cup-2014.gif" },
  { year: 2018, event_type: "World Cup", label: "World Cup 2018", url: "logos/world-cup-2018.png" },
  { year: 2022, event_type: "World Cup", label: "World Cup 2022", url: "logos/world-cup-2022.png" },
  { year: 2026, event_type: "World Cup", label: "World Cup 2026", url: "logos/world-cup-2026.png" },
  { year: 1896, event_type: "Summer Olympics", label: "Summer Olympics 1896", url: "logos/summer-olympics-1896.gif" },
  { year: 1904, event_type: "Summer Olympics", label: "Summer Olympics 1904", url: "logos/summer-olympics-1904.gif" },
  { year: 1908, event_type: "Summer Olympics", label: "Summer Olympics 1908", url: "logos/summer-olympics-1908.gif" },
  { year: 1912, event_type: "Summer Olympics", label: "Summer Olympics 1912", url: "logos/summer-olympics-1912.gif" },
  { year: 1920, event_type: "Summer Olympics", label: "Summer Olympics 1920", url: "logos/summer-olympics-1920.gif" },
  { year: 1924, event_type: "Summer Olympics", label: "Summer Olympics 1924", url: "logos/summer-olympics-1924.gif" },
  { year: 1928, event_type: "Summer Olympics", label: "Summer Olympics 1928", url: "logos/summer-olympics-1928.gif" },
  { year: 1932, event_type: "Summer Olympics", label: "Summer Olympics 1932", url: "logos/summer-olympics-1932.gif" },
  { year: 1936, event_type: "Summer Olympics", label: "Summer Olympics 1936", url: "logos/summer-olympics-1936.gif" },
  { year: 1948, event_type: "Summer Olympics", label: "Summer Olympics 1948", url: "logos/summer-olympics-1948.gif" },
  { year: 1952, event_type: "Summer Olympics", label: "Summer Olympics 1952", url: "logos/summer-olympics-1952.gif" },
  { year: 1956, event_type: "Summer Olympics", label: "Summer Olympics 1956", url: "logos/summer-olympics-1956.gif" },
  { year: 1960, event_type: "Summer Olympics", label: "Summer Olympics 1960", url: "logos/summer-olympics-1960.gif" },
  { year: 1964, event_type: "Summer Olympics", label: "Summer Olympics 1964", url: "logos/summer-olympics-1964.gif" },
  { year: 1968, event_type: "Summer Olympics", label: "Summer Olympics 1968", url: "logos/summer-olympics-1968.gif" },
  { year: 1972, event_type: "Summer Olympics", label: "Summer Olympics 1972", url: "logos/summer-olympics-1972.gif" },
  { year: 1976, event_type: "Summer Olympics", label: "Summer Olympics 1976", url: "logos/summer-olympics-1976.gif" },
  { year: 1980, event_type: "Summer Olympics", label: "Summer Olympics 1980", url: "logos/summer-olympics-1980.gif" },
  { year: 1984, event_type: "Summer Olympics", label: "Summer Olympics 1984", url: "logos/summer-olympics-1984.gif" },
  { year: 1988, event_type: "Summer Olympics", label: "Summer Olympics 1988", url: "logos/summer-olympics-1988.gif" },
  { year: 1992, event_type: "Summer Olympics", label: "Summer Olympics 1992", url: "logos/summer-olympics-1992.gif" },
  { year: 1996, event_type: "Summer Olympics", label: "Summer Olympics 1996", url: "logos/summer-olympics-1996.gif" },
  { year: 2000, event_type: "Summer Olympics", label: "Summer Olympics 2000", url: "logos/summer-olympics-2000.gif" },
  { year: 2004, event_type: "Summer Olympics", label: "Summer Olympics 2004", url: "logos/summer-olympics-2004.gif" },
  { year: 2008, event_type: "Summer Olympics", label: "Summer Olympics 2008", url: "logos/summer-olympics-2008.gif" },
  { year: 2012, event_type: "Summer Olympics", label: "Summer Olympics 2012", url: "logos/summer-olympics-2012.gif" },
  { year: 2016, event_type: "Summer Olympics", label: "Summer Olympics 2016", url: "logos/summer-olympics-2016.gif" },
  { year: 2021, event_type: "Summer Olympics", label: "Summer Olympics 2021", url: "logos/summer-olympics-2021.gif" },
  { year: 2024, event_type: "Summer Olympics", label: "Summer Olympics 2024", url: "logos/summer-olympics-2024.gif" },
  { year: 2028, event_type: "Summer Olympics", label: "Summer Olympics 2028", url: "logos/summer-olympics-2028.gif" },
  { year: 1924, event_type: "Winter Olympics", label: "Winter Olympics 1924 (Chamonix)", url: "logos/winter-olympics-1924.gif" },
  { year: 1928, event_type: "Winter Olympics", label: "Winter Olympics 1928 (St. Moritz)", url: "logos/winter-olympics-1928.gif" },
  { year: 1932, event_type: "Winter Olympics", label: "Winter Olympics 1932 (Lake Placid)", url: "logos/winter-olympics-1932.gif" },
  { year: 1936, event_type: "Winter Olympics", label: "Winter Olympics 1936 (Garmisch)", url: "logos/winter-olympics-1936.gif" },
  { year: 1948, event_type: "Winter Olympics", label: "Winter Olympics 1948 (St. Moritz)", url: "logos/winter-olympics-1948.gif" },
  { year: 1952, event_type: "Winter Olympics", label: "Winter Olympics 1952 (Oslo)", url: "logos/winter-olympics-1952.gif" },
  { year: 1956, event_type: "Winter Olympics", label: "Winter Olympics 1956 (Cortina d'Ampezzo)", url: "logos/winter-olympics-1956.gif" },
  { year: 1960, event_type: "Winter Olympics", label: "Winter Olympics 1960 (Squaw Valley)", url: "logos/winter-olympics-1960.gif" },
  { year: 1964, event_type: "Winter Olympics", label: "Winter Olympics 1964 (Innsbruck)", url: "logos/winter-olympics-1964.gif" },
  { year: 1968, event_type: "Winter Olympics", label: "Winter Olympics 1968 (Grenoble)", url: "logos/winter-olympics-1968.gif" },
  { year: 1972, event_type: "Winter Olympics", label: "Winter Olympics 1972 (Sapporo)", url: "logos/winter-olympics-1972.gif" },
  { year: 1976, event_type: "Winter Olympics", label: "Winter Olympics 1976 (Innsbruck)", url: "logos/winter-olympics-1976.gif" },
  { year: 1980, event_type: "Winter Olympics", label: "Winter Olympics 1980 (Lake Placid)", url: "logos/winter-olympics-1980.gif" },
  { year: 1984, event_type: "Winter Olympics", label: "Winter Olympics 1984 (Sarajevo)", url: "logos/winter-olympics-1984.gif" },
  { year: 1988, event_type: "Winter Olympics", label: "Winter Olympics 1988 (Calgary)", url: "logos/winter-olympics-1988.gif" },
  { year: 1992, event_type: "Winter Olympics", label: "Winter Olympics 1992 (Albertville)", url: "logos/winter-olympics-1992.gif" },
  { year: 1994, event_type: "Winter Olympics", label: "Winter Olympics 1994 (Lillehammer)", url: "logos/winter-olympics-1994.gif" },
  { year: 1998, event_type: "Winter Olympics", label: "Winter Olympics 1998 (Nagano)", url: "logos/winter-olympics-1998.gif" },
  { year: 2002, event_type: "Winter Olympics", label: "Winter Olympics 2002 (Salt Lake)", url: "logos/winter-olympics-2002.gif" },
  { year: 2006, event_type: "Winter Olympics", label: "Winter Olympics 2006 (Torino)", url: "logos/winter-olympics-2006.gif" },
  { year: 2010, event_type: "Winter Olympics", label: "Winter Olympics 2010 (Vancouver)", url: "logos/winter-olympics-2010.gif" },
  { year: 2014, event_type: "Winter Olympics", label: "Winter Olympics 2014 (Sochi)", url: "logos/winter-olympics-2014.gif" },
  { year: 2018, event_type: "Winter Olympics", label: "Winter Olympics 2018 (Pyeongchang)", url: "logos/winter-olympics-2018.gif" },
  { year: 2022, event_type: "Winter Olympics", label: "Winter Olympics 2022 (Beijing)", url: "logos/winter-olympics-2022.gif" },
  { year: 2026, event_type: "Winter Olympics", label: "Winter Olympics 2026 (Milano Cortina)", url: "logos/winter-olympics-2026.gif" },
  { year: 1979, event_type: "Men's Final Four", label: "Men's Final Four 1979", url: "logos/men-s-final-four-1979.gif" },
  { year: 1980, event_type: "Men's Final Four", label: "Men's Final Four 1980", url: "logos/men-s-final-four-1980.gif" },
  { year: 1981, event_type: "Men's Final Four", label: "Men's Final Four 1981", url: "logos/men-s-final-four-1981.gif" },
  { year: 1982, event_type: "Men's Final Four", label: "Men's Final Four 1982", url: "logos/men-s-final-four-1982.gif" },
  { year: 1983, event_type: "Men's Final Four", label: "Men's Final Four 1983", url: "logos/men-s-final-four-1983.gif" },
  { year: 1984, event_type: "Men's Final Four", label: "Men's Final Four 1984", url: "logos/men-s-final-four-1984.gif" },
  { year: 1985, event_type: "Men's Final Four", label: "Men's Final Four 1985", url: "logos/men-s-final-four-1985.gif" },
  { year: 1986, event_type: "Men's Final Four", label: "Men's Final Four 1986", url: "logos/men-s-final-four-1986.gif" },
  { year: 1987, event_type: "Men's Final Four", label: "Men's Final Four 1987", url: "logos/men-s-final-four-1987.gif" },
  { year: 1988, event_type: "Men's Final Four", label: "Men's Final Four 1988", url: "logos/men-s-final-four-1988.gif" },
  { year: 1989, event_type: "Men's Final Four", label: "Men's Final Four 1989", url: "logos/men-s-final-four-1989.gif" },
  { year: 1990, event_type: "Men's Final Four", label: "Men's Final Four 1990", url: "logos/men-s-final-four-1990.gif" },
  { year: 1991, event_type: "Men's Final Four", label: "Men's Final Four 1991", url: "logos/men-s-final-four-1991.gif" },
  { year: 1992, event_type: "Men's Final Four", label: "Men's Final Four 1992", url: "logos/men-s-final-four-1992.gif" },
  { year: 1993, event_type: "Men's Final Four", label: "Men's Final Four 1993", url: "logos/men-s-final-four-1993.gif" },
  { year: 1994, event_type: "Men's Final Four", label: "Men's Final Four 1994", url: "logos/men-s-final-four-1994.gif" },
  { year: 1995, event_type: "Men's Final Four", label: "Men's Final Four 1995", url: "logos/men-s-final-four-1995.gif" },
  { year: 1996, event_type: "Men's Final Four", label: "Men's Final Four 1996", url: "logos/men-s-final-four-1996.gif" },
  { year: 1997, event_type: "Men's Final Four", label: "Men's Final Four 1997", url: "logos/men-s-final-four-1997.gif" },
  { year: 1998, event_type: "Men's Final Four", label: "Men's Final Four 1998", url: "logos/men-s-final-four-1998.gif" },
  { year: 1999, event_type: "Men's Final Four", label: "Men's Final Four 1999", url: "logos/men-s-final-four-1999.gif" },
  { year: 2000, event_type: "Men's Final Four", label: "Men's Final Four 2000", url: "logos/men-s-final-four-2000.gif" },
  { year: 2001, event_type: "Men's Final Four", label: "Men's Final Four 2001", url: "logos/men-s-final-four-2001.gif" },
  { year: 2002, event_type: "Men's Final Four", label: "Men's Final Four 2002", url: "logos/men-s-final-four-2002.gif" },
  { year: 2003, event_type: "Men's Final Four", label: "Men's Final Four 2003", url: "logos/men-s-final-four-2003.gif" },
  { year: 2004, event_type: "Men's Final Four", label: "Men's Final Four 2004", url: "logos/men-s-final-four-2004.gif" },
  { year: 2005, event_type: "Men's Final Four", label: "Men's Final Four 2005", url: "logos/men-s-final-four-2005.gif" },
  { year: 2006, event_type: "Men's Final Four", label: "Men's Final Four 2006", url: "logos/men-s-final-four-2006.gif" },
  { year: 2007, event_type: "Men's Final Four", label: "Men's Final Four 2007", url: "logos/men-s-final-four-2007.gif" },
  { year: 2008, event_type: "Men's Final Four", label: "Men's Final Four 2008", url: "logos/men-s-final-four-2008.gif" },
  { year: 2009, event_type: "Men's Final Four", label: "Men's Final Four 2009", url: "logos/men-s-final-four-2009.gif" },
  { year: 2010, event_type: "Men's Final Four", label: "Men's Final Four 2010", url: "logos/men-s-final-four-2010.gif" },
  { year: 2011, event_type: "Men's Final Four", label: "Men's Final Four 2011", url: "logos/men-s-final-four-2011.gif" },
  { year: 2012, event_type: "Men's Final Four", label: "Men's Final Four 2012", url: "logos/men-s-final-four-2012.gif" },
  { year: 2013, event_type: "Men's Final Four", label: "Men's Final Four 2013", url: "logos/men-s-final-four-2013.gif" },
  { year: 2014, event_type: "Men's Final Four", label: "Men's Final Four 2014", url: "logos/men-s-final-four-2014.gif" },
  { year: 2015, event_type: "Men's Final Four", label: "Men's Final Four 2015", url: "logos/men-s-final-four-2015.gif" },
  { year: 2016, event_type: "Men's Final Four", label: "Men's Final Four 2016", url: "logos/men-s-final-four-2016.gif" },
  { year: 2017, event_type: "Men's Final Four", label: "Men's Final Four 2017", url: "logos/men-s-final-four-2017.gif" },
  { year: 2018, event_type: "Men's Final Four", label: "Men's Final Four 2018", url: "logos/men-s-final-four-2018.gif" },
  { year: 2019, event_type: "Men's Final Four", label: "Men's Final Four 2019", url: "logos/men-s-final-four-2019.gif" },
  { year: 2020, event_type: "Men's Final Four", label: "Men's Final Four 2020", url: "logos/men-s-final-four-2020.gif" },
  { year: 2021, event_type: "Men's Final Four", label: "Men's Final Four 2021", url: "logos/men-s-final-four-2021.gif" },
  { year: 2022, event_type: "Men's Final Four", label: "Men's Final Four 2022", url: "logos/men-s-final-four-2022.gif" },
  { year: 2023, event_type: "Men's Final Four", label: "Men's Final Four 2023", url: "logos/men-s-final-four-2023.gif" },
  { year: 2024, event_type: "Men's Final Four", label: "Men's Final Four 2024", url: "logos/men-s-final-four-2024.gif" },
  { year: 2025, event_type: "Men's Final Four", label: "Men's Final Four 2025", url: "logos/men-s-final-four-2025.gif" },
  { year: 2026, event_type: "Men's Final Four", label: "Men's Final Four 2026", url: "logos/men-s-final-four-2026.gif" },
  { year: 1974, event_type: "World Series", label: "World Series 1974", url: "logos/world-series-1974.gif" },
  { year: 1975, event_type: "World Series", label: "World Series 1975", url: "logos/world-series-1975.gif" },
  { year: 1976, event_type: "World Series", label: "World Series 1976", url: "logos/world-series-1976.gif" },
  { year: 1977, event_type: "World Series", label: "World Series 1977", url: "logos/world-series-1977.gif" },
  { year: 1978, event_type: "World Series", label: "World Series 1978", url: "logos/world-series-1978.gif" },
  { year: 1979, event_type: "World Series", label: "World Series 1979", url: "logos/world-series-1979.gif" },
  { year: 1980, event_type: "World Series", label: "World Series 1980", url: "logos/world-series-1980.gif" },
  { year: 1981, event_type: "World Series", label: "World Series 1981", url: "logos/world-series-1981.gif" },
  { year: 1982, event_type: "World Series", label: "World Series 1982", url: "logos/world-series-1982.gif" },
  { year: 1983, event_type: "World Series", label: "World Series 1983", url: "logos/world-series-1983.gif" },
  { year: 1984, event_type: "World Series", label: "World Series 1984", url: "logos/world-series-1984.gif" },
  { year: 1985, event_type: "World Series", label: "World Series 1985", url: "logos/world-series-1985.gif" },
  { year: 1986, event_type: "World Series", label: "World Series 1986", url: "logos/world-series-1986.gif" },
  { year: 1987, event_type: "World Series", label: "World Series 1987", url: "logos/world-series-1987.png" },
  { year: 1988, event_type: "World Series", label: "World Series 1988", url: "logos/world-series-1988.png" },
  { year: 1989, event_type: "World Series", label: "World Series 1989", url: "logos/world-series-1989.png" },
  { year: 1990, event_type: "World Series", label: "World Series 1990", url: "logos/world-series-1990.png" },
  { year: 1991, event_type: "World Series", label: "World Series 1991", url: "logos/world-series-1991.png" },
  { year: 1992, event_type: "World Series", label: "World Series 1992", url: "logos/world-series-1992.png" },
  { year: 1993, event_type: "World Series", label: "World Series 1993", url: "logos/world-series-1993.png" },
  { year: 1995, event_type: "World Series", label: "World Series 1995", url: "logos/world-series-1995.png" },
  { year: 1996, event_type: "World Series", label: "World Series 1996", url: "logos/world-series-1996.png" },
  { year: 1997, event_type: "World Series", label: "World Series 1997", url: "logos/world-series-1997.png" },
  { year: 1998, event_type: "World Series", label: "World Series 1998", url: "logos/world-series-1998.png" },
  { year: 1999, event_type: "World Series", label: "World Series 1999", url: "logos/world-series-1999.png" },
  { year: 2000, event_type: "World Series", label: "World Series 2000", url: "logos/world-series-2000.png" },
  { year: 2001, event_type: "World Series", label: "World Series 2001", url: "logos/world-series-2001.png" },
  { year: 2002, event_type: "World Series", label: "World Series 2002", url: "logos/world-series-2002.gif" },
  { year: 2003, event_type: "World Series", label: "World Series 2003", url: "logos/world-series-2003.gif" },
  { year: 2004, event_type: "World Series", label: "World Series 2004", url: "logos/world-series-2004.gif" },
  { year: 2005, event_type: "World Series", label: "World Series 2005", url: "logos/world-series-2005.gif" },
  { year: 2006, event_type: "World Series", label: "World Series 2006", url: "logos/world-series-2006.gif" },
  { year: 2007, event_type: "World Series", label: "World Series 2007", url: "logos/world-series-2007.gif" },
  { year: 2008, event_type: "World Series", label: "World Series 2008", url: "logos/world-series-2008.gif" },
  { year: 2009, event_type: "World Series", label: "World Series 2009", url: "logos/world-series-2009.gif" },
  { year: 2010, event_type: "World Series", label: "World Series 2010", url: "logos/world-series-2010.gif" },
  { year: 2011, event_type: "World Series", label: "World Series 2011", url: "logos/world-series-2011.gif" },
  { year: 2012, event_type: "World Series", label: "World Series 2012", url: "logos/world-series-2012.gif" },
  { year: 2013, event_type: "World Series", label: "World Series 2013", url: "logos/world-series-2013.gif" },
  { year: 2014, event_type: "World Series", label: "World Series 2014", url: "logos/world-series-2014.gif" },
  { year: 2015, event_type: "World Series", label: "World Series 2015", url: "logos/world-series-2015.gif" },
  { year: 2016, event_type: "World Series", label: "World Series 2016", url: "logos/world-series-2016.gif" },
  { year: 2017, event_type: "World Series", label: "World Series 2017", url: "logos/world-series-2017.gif" },
  { year: 2018, event_type: "World Series", label: "World Series 2018", url: "logos/world-series-2018.gif" },
  { year: 2019, event_type: "World Series", label: "World Series 2019", url: "logos/world-series-2019.gif" },
  { year: 2020, event_type: "World Series", label: "World Series 2020", url: "logos/world-series-2020.gif" },
  { year: 2021, event_type: "World Series", label: "World Series 2021", url: "logos/world-series-2021.gif" },
  { year: 2022, event_type: "World Series", label: "World Series 2022", url: "logos/world-series-2022.gif" },
  { year: 2023, event_type: "World Series", label: "World Series 2023", url: "logos/world-series-2023.gif" },
  { year: 2024, event_type: "World Series", label: "World Series 2024", url: "logos/world-series-2024.gif" },
  { year: 2025, event_type: "World Series", label: "World Series 2025", url: "logos/world-series-2025.png" },
  { year: 2026, event_type: "World Series", label: "World Series 2026", url: "logos/world-series-2026.png" },
  { year: 1967, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1967", url: "logos/nba-all-star-game-1967.gif" },
  { year: 1974, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1974", url: "logos/nba-all-star-game-1974.gif" },
  { year: 1975, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1975", url: "logos/nba-all-star-game-1975.gif" },
  { year: 1976, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1976", url: "logos/nba-all-star-game-1976.gif" },
  { year: 1977, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1977", url: "logos/nba-all-star-game-1977.gif" },
  { year: 1979, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1979", url: "logos/nba-all-star-game-1979.gif" },
  { year: 1980, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1980", url: "logos/nba-all-star-game-1980.gif" },
  { year: 1981, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1981", url: "logos/nba-all-star-game-1981.gif" },
  { year: 1982, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1982", url: "logos/nba-all-star-game-1982.gif" },
  { year: 1983, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1983", url: "logos/nba-all-star-game-1983.gif" },
  { year: 1984, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1984", url: "logos/nba-all-star-game-1984.gif" },
  { year: 1985, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1985", url: "logos/nba-all-star-game-1985.gif" },
  { year: 1986, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1986", url: "logos/nba-all-star-game-1986.gif" },
  { year: 1987, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1987", url: "logos/nba-all-star-game-1987.gif" },
  { year: 1988, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1988", url: "logos/nba-all-star-game-1988.gif" },
  { year: 1989, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1989", url: "logos/nba-all-star-game-1989.gif" },
  { year: 1990, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1990", url: "logos/nba-all-star-game-1990.gif" },
  { year: 1991, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1991", url: "logos/nba-all-star-game-1991.gif" },
  { year: 1992, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1992", url: "logos/nba-all-star-game-1992.gif" },
  { year: 1993, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1993", url: "logos/nba-all-star-game-1993.gif" },
  { year: 1994, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1994", url: "logos/nba-all-star-game-1994.gif" },
  { year: 1995, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1995", url: "logos/nba-all-star-game-1995.gif" },
  { year: 1996, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1996", url: "logos/nba-all-star-game-1996.gif" },
  { year: 1997, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1997", url: "logos/nba-all-star-game-1997.gif" },
  { year: 1998, event_type: "NBA All-Star Game", label: "NBA All-Star Game 1998", url: "logos/nba-all-star-game-1998.gif" },
  { year: 2000, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2000", url: "logos/nba-all-star-game-2000.gif" },
  { year: 2001, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2001", url: "logos/nba-all-star-game-2001.gif" },
  { year: 2002, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2002", url: "logos/nba-all-star-game-2002.gif" },
  { year: 2003, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2003", url: "logos/nba-all-star-game-2003.gif" },
  { year: 2004, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2004", url: "logos/nba-all-star-game-2004.gif" },
  { year: 2005, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2005", url: "logos/nba-all-star-game-2005.gif" },
  { year: 2006, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2006", url: "logos/nba-all-star-game-2006.gif" },
  { year: 2007, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2007", url: "logos/nba-all-star-game-2007.gif" },
  { year: 2008, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2008", url: "logos/nba-all-star-game-2008.gif" },
  { year: 2009, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2009", url: "logos/nba-all-star-game-2009.gif" },
  { year: 2010, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2010", url: "logos/nba-all-star-game-2010.gif" },
  { year: 2011, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2011", url: "logos/nba-all-star-game-2011.gif" },
  { year: 2012, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2012", url: "logos/nba-all-star-game-2012.gif" },
  { year: 2013, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2013", url: "logos/nba-all-star-game-2013.gif" },
  { year: 2014, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2014", url: "logos/nba-all-star-game-2014.gif" },
  { year: 2015, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2015", url: "logos/nba-all-star-game-2015.gif" },
  { year: 2016, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2016", url: "logos/nba-all-star-game-2016.gif" },
  { year: 2017, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2017", url: "logos/nba-all-star-game-2017.gif" },
  { year: 2018, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2018", url: "logos/nba-all-star-game-2018.gif" },
  { year: 2019, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2019", url: "logos/nba-all-star-game-2019.gif" },
  { year: 2020, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2020", url: "logos/nba-all-star-game-2020.gif" },
  { year: 2021, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2021", url: "logos/nba-all-star-game-2021.gif" },
  { year: 2022, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2022", url: "logos/nba-all-star-game-2022.gif" },
  { year: 2023, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2023", url: "logos/nba-all-star-game-2023.gif" },
  { year: 2024, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2024", url: "logos/nba-all-star-game-2024.gif" },
  { year: 2025, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2025", url: "logos/nba-all-star-game-2025.gif" },
  { year: 2026, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2026", url: "logos/nba-all-star-game-2026.gif" },
  { year: 2027, event_type: "NBA All-Star Game", label: "NBA All-Star Game 2027", url: "logos/nba-all-star-game-2027.png" },
  { year: 1952, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1952", url: "logos/mlb-all-star-game-1952.gif" },
  { year: 1953, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1953", url: "logos/mlb-all-star-game-1953.gif" },
  { year: 1954, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1954", url: "logos/mlb-all-star-game-1954.gif" },
  { year: 1955, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1955", url: "logos/mlb-all-star-game-1955.gif" },
  { year: 1956, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1956", url: "logos/mlb-all-star-game-1956.gif" },
  { year: 1957, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1957", url: "logos/mlb-all-star-game-1957.gif" },
  { year: 1958, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1958", url: "logos/mlb-all-star-game-1958.gif" },
  { year: 1959, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1959", url: "logos/mlb-all-star-game-1959-1.gif" },
  { year: 1959, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1959", url: "logos/mlb-all-star-game-1959-2.gif" },
  { year: 1960, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1960", url: "logos/mlb-all-star-game-1960-1.gif" },
  { year: 1960, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1960", url: "logos/mlb-all-star-game-1960-2.gif" },
  { year: 1961, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1961", url: "logos/mlb-all-star-game-1961-1.gif" },
  { year: 1961, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1961", url: "logos/mlb-all-star-game-1961-2.gif" },
  { year: 1962, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1962", url: "logos/mlb-all-star-game-1962.gif" },
  { year: 1963, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1963", url: "logos/mlb-all-star-game-1963.gif" },
  { year: 1964, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1964", url: "logos/mlb-all-star-game-1964.gif" },
  { year: 1965, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1965", url: "logos/mlb-all-star-game-1965.gif" },
  { year: 1966, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1966", url: "logos/mlb-all-star-game-1966.gif" },
  { year: 1967, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1967", url: "logos/mlb-all-star-game-1967.gif" },
  { year: 1968, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1968", url: "logos/mlb-all-star-game-1968.gif" },
  { year: 1969, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1969", url: "logos/mlb-all-star-game-1969.gif" },
  { year: 1970, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1970", url: "logos/mlb-all-star-game-1970.gif" },
  { year: 1971, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1971", url: "logos/mlb-all-star-game-1971.gif" },
  { year: 1972, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1972", url: "logos/mlb-all-star-game-1972.gif" },
  { year: 1973, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1973", url: "logos/mlb-all-star-game-1973.gif" },
  { year: 1974, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1974", url: "logos/mlb-all-star-game-1974.gif" },
  { year: 1975, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1975", url: "logos/mlb-all-star-game-1975.gif" },
  { year: 1976, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1976", url: "logos/mlb-all-star-game-1976.gif" },
  { year: 1977, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1977", url: "logos/mlb-all-star-game-1977.gif" },
  { year: 1978, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1978", url: "logos/mlb-all-star-game-1978.gif" },
  { year: 1979, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1979", url: "logos/mlb-all-star-game-1979.gif" },
  { year: 1980, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1980", url: "logos/mlb-all-star-game-1980.gif" },
  { year: 1981, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1981", url: "logos/mlb-all-star-game-1981.gif" },
  { year: 1982, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1982", url: "logos/mlb-all-star-game-1982.gif" },
  { year: 1983, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1983", url: "logos/mlb-all-star-game-1983.gif" },
  { year: 1984, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1984", url: "logos/mlb-all-star-game-1984.gif" },
  { year: 1985, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1985", url: "logos/mlb-all-star-game-1985.gif" },
  { year: 1986, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1986", url: "logos/mlb-all-star-game-1986.gif" },
  { year: 1987, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1987", url: "logos/mlb-all-star-game-1987.gif" },
  { year: 1988, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1988", url: "logos/mlb-all-star-game-1988.gif" },
  { year: 1989, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1989", url: "logos/mlb-all-star-game-1989.gif" },
  { year: 1990, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1990", url: "logos/mlb-all-star-game-1990.gif" },
  { year: 1991, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1991", url: "logos/mlb-all-star-game-1991.gif" },
  { year: 1992, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1992", url: "logos/mlb-all-star-game-1992.gif" },
  { year: 1993, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1993", url: "logos/mlb-all-star-game-1993.gif" },
  { year: 1994, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1994", url: "logos/mlb-all-star-game-1994.gif" },
  { year: 1995, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1995", url: "logos/mlb-all-star-game-1995.gif" },
  { year: 1996, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1996", url: "logos/mlb-all-star-game-1996.gif" },
  { year: 1997, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1997", url: "logos/mlb-all-star-game-1997.gif" },
  { year: 1998, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1998", url: "logos/mlb-all-star-game-1998.gif" },
  { year: 1999, event_type: "MLB All-Star Game", label: "MLB All-Star Game 1999", url: "logos/mlb-all-star-game-1999.gif" },
  { year: 2000, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2000", url: "logos/mlb-all-star-game-2000.gif" },
  { year: 2001, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2001", url: "logos/mlb-all-star-game-2001.gif" },
  { year: 2002, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2002", url: "logos/mlb-all-star-game-2002.gif" },
  { year: 2003, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2003", url: "logos/mlb-all-star-game-2003.gif" },
  { year: 2004, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2004", url: "logos/mlb-all-star-game-2004.gif" },
  { year: 2005, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2005", url: "logos/mlb-all-star-game-2005.gif" },
  { year: 2006, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2006", url: "logos/mlb-all-star-game-2006.gif" },
  { year: 2007, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2007", url: "logos/mlb-all-star-game-2007.gif" },
  { year: 2008, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2008", url: "logos/mlb-all-star-game-2008.gif" },
  { year: 2009, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2009", url: "logos/mlb-all-star-game-2009.gif" },
  { year: 2010, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2010", url: "logos/mlb-all-star-game-2010.gif" },
  { year: 2011, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2011", url: "logos/mlb-all-star-game-2011.gif" },
  { year: 2012, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2012", url: "logos/mlb-all-star-game-2012.gif" },
  { year: 2013, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2013", url: "logos/mlb-all-star-game-2013.gif" },
  { year: 2014, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2014", url: "logos/mlb-all-star-game-2014.png" },
  { year: 2015, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2015", url: "logos/mlb-all-star-game-2015.gif" },
  { year: 2016, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2016", url: "logos/mlb-all-star-game-2016.gif" },
  { year: 2017, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2017", url: "logos/mlb-all-star-game-2017.gif" },
  { year: 2018, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2018", url: "logos/mlb-all-star-game-2018.gif" },
  { year: 2019, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2019", url: "logos/mlb-all-star-game-2019.gif" },
  { year: 2021, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2021", url: "logos/mlb-all-star-game-2021.gif" },
  { year: 2022, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2022", url: "logos/mlb-all-star-game-2022.gif" },
  { year: 2023, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2023", url: "logos/mlb-all-star-game-2023.gif" },
  { year: 2024, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2024", url: "logos/mlb-all-star-game-2024.gif" },
  { year: 2025, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2025", url: "logos/mlb-all-star-game-2025.gif" },
  { year: 2026, event_type: "MLB All-Star Game", label: "MLB All-Star Game 2026", url: "logos/mlb-all-star-game-2026.png" },
  { year: 1972, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1972", url: "logos/nhl-all-star-game-1972.gif" },
  { year: 1974, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1974", url: "logos/nhl-all-star-game-1974.gif" },
  { year: 1976, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1976", url: "logos/nhl-all-star-game-1976.png" },
  { year: 1977, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1977", url: "logos/nhl-all-star-game-1977.png" },
  { year: 1979, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1979", url: "logos/nhl-all-star-game-1979.png" },
  { year: 1980, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1980", url: "logos/nhl-all-star-game-1980.png" },
  { year: 1981, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1981", url: "logos/nhl-all-star-game-1981.png" },
  { year: 1982, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1982", url: "logos/nhl-all-star-game-1982.png" },
  { year: 1983, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1983", url: "logos/nhl-all-star-game-1983.png" },
  { year: 1984, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1984", url: "logos/nhl-all-star-game-1984.png" },
  { year: 1985, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1985", url: "logos/nhl-all-star-game-1985.png" },
  { year: 1986, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1986", url: "logos/nhl-all-star-game-1986.png" },
  { year: 1987, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1987", url: "logos/nhl-all-star-game-1987.png" },
  { year: 1988, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1988", url: "logos/nhl-all-star-game-1988.png" },
  { year: 1989, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1989", url: "logos/nhl-all-star-game-1989.png" },
  { year: 1990, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1990", url: "logos/nhl-all-star-game-1990.png" },
  { year: 1991, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1991", url: "logos/nhl-all-star-game-1991.gif" },
  { year: 1992, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1992", url: "logos/nhl-all-star-game-1992.gif" },
  { year: 1993, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1993", url: "logos/nhl-all-star-game-1993.gif" },
  { year: 1994, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1994", url: "logos/nhl-all-star-game-1994.gif" },
  { year: 1996, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1996", url: "logos/nhl-all-star-game-1996.gif" },
  { year: 1997, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1997", url: "logos/nhl-all-star-game-1997.gif" },
  { year: 1998, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1998", url: "logos/nhl-all-star-game-1998.gif" },
  { year: 1999, event_type: "NHL All-Star Game", label: "NHL All-Star Game 1999", url: "logos/nhl-all-star-game-1999.gif" },
  { year: 2000, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2000", url: "logos/nhl-all-star-game-2000.gif" },
  { year: 2001, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2001", url: "logos/nhl-all-star-game-2001.gif" },
  { year: 2002, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2002", url: "logos/nhl-all-star-game-2002.gif" },
  { year: 2003, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2003", url: "logos/nhl-all-star-game-2003.gif" },
  { year: 2004, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2004", url: "logos/nhl-all-star-game-2004.gif" },
  { year: 2007, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2007", url: "logos/nhl-all-star-game-2007.gif" },
  { year: 2008, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2008", url: "logos/nhl-all-star-game-2008.gif" },
  { year: 2009, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2009", url: "logos/nhl-all-star-game-2009.gif" },
  { year: 2011, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2011", url: "logos/nhl-all-star-game-2011.gif" },
  { year: 2012, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2012", url: "logos/nhl-all-star-game-2012.gif" },
  { year: 2015, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2015", url: "logos/nhl-all-star-game-2015.gif" },
  { year: 2016, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2016", url: "logos/nhl-all-star-game-2016.gif" },
  { year: 2017, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2017", url: "logos/nhl-all-star-game-2017.gif" },
  { year: 2018, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2018", url: "logos/nhl-all-star-game-2018.gif" },
  { year: 2019, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2019", url: "logos/nhl-all-star-game-2019.gif" },
  { year: 2020, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2020", url: "logos/nhl-all-star-game-2020.gif" },
  { year: 2022, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2022", url: "logos/nhl-all-star-game-2022.gif" },
  { year: 2023, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2023", url: "logos/nhl-all-star-game-2023.gif" },
  { year: 2024, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2024", url: "logos/nhl-all-star-game-2024.gif" },
  { year: 2025, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2025", url: "logos/nhl-all-star-game-2025.gif" },
  { year: 2027, event_type: "NHL All-Star Game", label: "NHL All-Star Game 2027", url: "logos/nhl-all-star-game-2027.png" },
  { year: 1986, event_type: "NBA Finals", label: "NBA Finals 1986", url: "logos/nba-finals-1986.gif" },
  { year: 1987, event_type: "NBA Finals", label: "NBA Finals 1987", url: "logos/nba-finals-1987.gif" },
  { year: 1988, event_type: "NBA Finals", label: "NBA Finals 1988", url: "logos/nba-finals-1988.gif" },
  { year: 1989, event_type: "NBA Finals", label: "NBA Finals 1989", url: "logos/nba-finals-1989.gif" },
  { year: 1990, event_type: "NBA Finals", label: "NBA Finals 1990", url: "logos/nba-finals-1990.gif" },
  { year: 1991, event_type: "NBA Finals", label: "NBA Finals 1991", url: "logos/nba-finals-1991.gif" },
  { year: 1992, event_type: "NBA Finals", label: "NBA Finals 1992", url: "logos/nba-finals-1992.gif" },
  { year: 1993, event_type: "NBA Finals", label: "NBA Finals 1993", url: "logos/nba-finals-1993.gif" },
  { year: 1994, event_type: "NBA Finals", label: "NBA Finals 1994", url: "logos/nba-finals-1994.gif" },
  { year: 1995, event_type: "NBA Finals", label: "NBA Finals 1995", url: "logos/nba-finals-1995.gif" },
  { year: 1996, event_type: "NBA Finals", label: "NBA Finals 1996", url: "logos/nba-finals-1996.gif" },
  { year: 1997, event_type: "NBA Finals", label: "NBA Finals 1997", url: "logos/nba-finals-1997.gif" },
  { year: 1998, event_type: "NBA Finals", label: "NBA Finals 1998", url: "logos/nba-finals-1998.gif" },
  { year: 1999, event_type: "NBA Finals", label: "NBA Finals 1999", url: "logos/nba-finals-1999.gif" },
  { year: 2000, event_type: "NBA Finals", label: "NBA Finals 2000", url: "logos/nba-finals-2000.gif" },
  { year: 2001, event_type: "NBA Finals", label: "NBA Finals 2001", url: "logos/nba-finals-2001.gif" },
  { year: 2002, event_type: "NBA Finals", label: "NBA Finals 2002", url: "logos/nba-finals-2002.gif" },
  { year: 2003, event_type: "NBA Finals", label: "NBA Finals 2003", url: "logos/nba-finals-2003.gif" },
  { year: 2004, event_type: "NBA Finals", label: "NBA Finals 2004", url: "logos/nba-finals-2004.gif" },
  { year: 2005, event_type: "NBA Finals", label: "NBA Finals 2005", url: "logos/nba-finals-2005.gif" },
  { year: 2006, event_type: "NBA Finals", label: "NBA Finals 2006", url: "logos/nba-finals-2006.gif" },
  { year: 2007, event_type: "NBA Finals", label: "NBA Finals 2007", url: "logos/nba-finals-2007.gif" },
  { year: 2008, event_type: "NBA Finals", label: "NBA Finals 2008", url: "logos/nba-finals-2008.gif" },
  { year: 2009, event_type: "NBA Finals", label: "NBA Finals 2009", url: "logos/nba-finals-2009.gif" },
  { year: 2010, event_type: "NBA Finals", label: "NBA Finals 2010", url: "logos/nba-finals-2010.gif" },
  { year: 2018, event_type: "NBA Finals", label: "NBA Finals 2018", url: "logos/nba-finals-2018.gif" },
  { year: 2019, event_type: "NBA Finals", label: "NBA Finals 2019", url: "logos/nba-finals-2019.gif" },
  { year: 2020, event_type: "NBA Finals", label: "NBA Finals 2020", url: "logos/nba-finals-2020.gif" },
  { year: 2021, event_type: "NBA Finals", label: "NBA Finals 2021", url: "logos/nba-finals-2021.gif" },
  { year: 2022, event_type: "NBA Finals", label: "NBA Finals 2022", url: "logos/nba-finals-2022.gif" },
  { year: 2023, event_type: "NBA Finals", label: "NBA Finals 2023", url: "logos/nba-finals-2023.gif" },
  { year: 2024, event_type: "NBA Finals", label: "NBA Finals 2024", url: "logos/nba-finals-2024.gif" },
  { year: 2025, event_type: "NBA Finals", label: "NBA Finals 2025", url: "logos/nba-finals-2025.gif" },
  { year: 2026, event_type: "NBA Finals", label: "NBA Finals 2026", url: "logos/nba-finals-2026.png" },
  { year: 2006, event_type: "WNBA Finals", label: "WNBA Finals 2006", url: "logos/wnba-finals-2006.gif" },
  { year: 2007, event_type: "WNBA Finals", label: "WNBA Finals 2007", url: "logos/wnba-finals-2007.gif" },
  { year: 2010, event_type: "WNBA Finals", label: "WNBA Finals 2010", url: "logos/wnba-finals-2010.gif" },
  { year: 2011, event_type: "WNBA Finals", label: "WNBA Finals 2011", url: "logos/wnba-finals-2011.gif" },
  { year: 2012, event_type: "WNBA Finals", label: "WNBA Finals 2012", url: "logos/wnba-finals-2012.gif" },
  { year: 2016, event_type: "WNBA Finals", label: "WNBA Finals 2016", url: "logos/wnba-finals-2016.gif" },
  { year: 2018, event_type: "WNBA Finals", label: "WNBA Finals 2018", url: "logos/wnba-finals-2018.gif" },
  { year: 2019, event_type: "WNBA Finals", label: "WNBA Finals 2019", url: "logos/wnba-finals-2019.gif" },
  { year: 2020, event_type: "WNBA Finals", label: "WNBA Finals 2020", url: "logos/wnba-finals-2020.gif" },
  { year: 2021, event_type: "WNBA Finals", label: "WNBA Finals 2021", url: "logos/wnba-finals-2021.gif" },
  { year: 2022, event_type: "WNBA Finals", label: "WNBA Finals 2022", url: "logos/wnba-finals-2022.gif" },
  { year: 2023, event_type: "WNBA Finals", label: "WNBA Finals 2023", url: "logos/wnba-finals-2023.gif" },
  { year: 2024, event_type: "WNBA Finals", label: "WNBA Finals 2024", url: "logos/wnba-finals-2024.gif" },
  { year: 1999, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 1999", url: "logos/wnba-all-star-game-1999.gif" },
  { year: 2000, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2000", url: "logos/wnba-all-star-game-2000.gif" },
  { year: 2001, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2001", url: "logos/wnba-all-star-game-2001.gif" },
  { year: 2002, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2002", url: "logos/wnba-all-star-game-2002.gif" },
  { year: 2003, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2003", url: "logos/wnba-all-star-game-2003.gif" },
  { year: 2004, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2004", url: "logos/wnba-all-star-game-2004.gif" },
  { year: 2005, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2005", url: "logos/wnba-all-star-game-2005.gif" },
  { year: 2006, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2006", url: "logos/wnba-all-star-game-2006.gif" },
  { year: 2007, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2007", url: "logos/wnba-all-star-game-2007.gif" },
  { year: 2009, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2009", url: "logos/wnba-all-star-game-2009.gif" },
  { year: 2010, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2010", url: "logos/wnba-all-star-game-2010.gif" },
  { year: 2011, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2011", url: "logos/wnba-all-star-game-2011.gif" },
  { year: 2013, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2013", url: "logos/wnba-all-star-game-2013.gif" },
  { year: 2014, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2014", url: "logos/wnba-all-star-game-2014.gif" },
  { year: 2015, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2015", url: "logos/wnba-all-star-game-2015.gif" },
  { year: 2017, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2017", url: "logos/wnba-all-star-game-2017.gif" },
  { year: 2018, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2018", url: "logos/wnba-all-star-game-2018.gif" },
  { year: 2019, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2019", url: "logos/wnba-all-star-game-2019.gif" },
  { year: 2021, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2021", url: "logos/wnba-all-star-game-2021.gif" },
  { year: 2022, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2022", url: "logos/wnba-all-star-game-2022.gif" },
  { year: 2023, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2023", url: "logos/wnba-all-star-game-2023.gif" },
  { year: 2024, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2024", url: "logos/wnba-all-star-game-2024.gif" },
  { year: 2025, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2025", url: "logos/wnba-all-star-game-2025.gif" },
  { year: 2026, event_type: "WNBA All-Star Game", label: "WNBA All-Star Game 2026", url: "logos/wnba-all-star-game-2026.png" },
  { year: 2004, event_type: "MLB Spring Training", label: "MLB Spring Training 2004", url: "logos/mlb-spring-training-2004.gif" },
  { year: 2010, event_type: "MLB Spring Training", label: "MLB Spring Training 2010", url: "logos/mlb-spring-training-2010.gif" },
  { year: 2011, event_type: "MLB Spring Training", label: "MLB Spring Training 2011", url: "logos/mlb-spring-training-2011.gif" },
  { year: 2012, event_type: "MLB Spring Training", label: "MLB Spring Training 2012", url: "logos/mlb-spring-training-2012.gif" },
  { year: 2013, event_type: "MLB Spring Training", label: "MLB Spring Training 2013", url: "logos/mlb-spring-training-2013.gif" },
  { year: 2014, event_type: "MLB Spring Training", label: "MLB Spring Training 2014", url: "logos/mlb-spring-training-2014.gif" },
  { year: 2015, event_type: "MLB Spring Training", label: "MLB Spring Training 2015", url: "logos/mlb-spring-training-2015.gif" },
  { year: 2016, event_type: "MLB Spring Training", label: "MLB Spring Training 2016", url: "logos/mlb-spring-training-2016.gif" },
  { year: 2017, event_type: "MLB Spring Training", label: "MLB Spring Training 2017", url: "logos/mlb-spring-training-2017.gif" },
  { year: 2018, event_type: "MLB Spring Training", label: "MLB Spring Training 2018", url: "logos/mlb-spring-training-2018.gif" },
  { year: 2019, event_type: "MLB Spring Training", label: "MLB Spring Training 2019", url: "logos/mlb-spring-training-2019.gif" },
  { year: 2020, event_type: "MLB Spring Training", label: "MLB Spring Training 2020", url: "logos/mlb-spring-training-2020.gif" },
  { year: 2021, event_type: "MLB Spring Training", label: "MLB Spring Training 2021", url: "logos/mlb-spring-training-2021.gif" },
  { year: 2022, event_type: "MLB Spring Training", label: "MLB Spring Training 2022", url: "logos/mlb-spring-training-2022.gif" },
  { year: 2023, event_type: "MLB Spring Training", label: "MLB Spring Training 2023", url: "logos/mlb-spring-training-2023.gif" },
  { year: 2024, event_type: "MLB Spring Training", label: "MLB Spring Training 2024", url: "logos/mlb-spring-training-2024.gif" },
  { year: 2025, event_type: "MLB Spring Training", label: "MLB Spring Training 2025", url: "logos/mlb-spring-training-2025.gif" },
  { year: 2026, event_type: "MLB Spring Training", label: "MLB Spring Training 2026", url: "logos/mlb-spring-training-2026.png" },
  { year: 1990, event_type: "NFL Draft", label: "NFL Draft 1990", url: "logos/nfl-draft-1990.gif" },
  { year: 1991, event_type: "NFL Draft", label: "NFL Draft 1991", url: "logos/nfl-draft-1991.gif" },
  { year: 1992, event_type: "NFL Draft", label: "NFL Draft 1992", url: "logos/nfl-draft-1992.gif" },
  { year: 1993, event_type: "NFL Draft", label: "NFL Draft 1993", url: "logos/nfl-draft-1993.gif" },
  { year: 1994, event_type: "NFL Draft", label: "NFL Draft 1994", url: "logos/nfl-draft-1994.gif" },
  { year: 1995, event_type: "NFL Draft", label: "NFL Draft 1995", url: "logos/nfl-draft-1995.gif" },
  { year: 1996, event_type: "NFL Draft", label: "NFL Draft 1996", url: "logos/nfl-draft-1996.gif" },
  { year: 1997, event_type: "NFL Draft", label: "NFL Draft 1997", url: "logos/nfl-draft-1997.gif" },
  { year: 1998, event_type: "NFL Draft", label: "NFL Draft 1998", url: "logos/nfl-draft-1998.gif" },
  { year: 1999, event_type: "NFL Draft", label: "NFL Draft 1999", url: "logos/nfl-draft-1999.gif" },
  { year: 2000, event_type: "NFL Draft", label: "NFL Draft 2000", url: "logos/nfl-draft-2000.gif" },
  { year: 2001, event_type: "NFL Draft", label: "NFL Draft 2001", url: "logos/nfl-draft-2001.gif" },
  { year: 2002, event_type: "NFL Draft", label: "NFL Draft 2002", url: "logos/nfl-draft-2002.gif" },
  { year: 2003, event_type: "NFL Draft", label: "NFL Draft 2003", url: "logos/nfl-draft-2003.gif" },
  { year: 2004, event_type: "NFL Draft", label: "NFL Draft 2004", url: "logos/nfl-draft-2004.gif" },
  { year: 2005, event_type: "NFL Draft", label: "NFL Draft 2005", url: "logos/nfl-draft-2005.gif" },
  { year: 2006, event_type: "NFL Draft", label: "NFL Draft 2006", url: "logos/nfl-draft-2006.gif" },
  { year: 2007, event_type: "NFL Draft", label: "NFL Draft 2007", url: "logos/nfl-draft-2007.gif" },
  { year: 2008, event_type: "NFL Draft", label: "NFL Draft 2008", url: "logos/nfl-draft-2008.gif" },
  { year: 2009, event_type: "NFL Draft", label: "NFL Draft 2009", url: "logos/nfl-draft-2009.gif" },
  { year: 2010, event_type: "NFL Draft", label: "NFL Draft 2010", url: "logos/nfl-draft-2010.gif" },
  { year: 2011, event_type: "NFL Draft", label: "NFL Draft 2011", url: "logos/nfl-draft-2011.gif" },
  { year: 2012, event_type: "NFL Draft", label: "NFL Draft 2012", url: "logos/nfl-draft-2012.gif" },
  { year: 2013, event_type: "NFL Draft", label: "NFL Draft 2013", url: "logos/nfl-draft-2013.gif" },
  { year: 2015, event_type: "NFL Draft", label: "NFL Draft 2015", url: "logos/nfl-draft-2015.gif" },
  { year: 2016, event_type: "NFL Draft", label: "NFL Draft 2016", url: "logos/nfl-draft-2016.gif" },
  { year: 2017, event_type: "NFL Draft", label: "NFL Draft 2017", url: "logos/nfl-draft-2017.gif" },
  { year: 2018, event_type: "NFL Draft", label: "NFL Draft 2018", url: "logos/nfl-draft-2018.gif" },
  { year: 2021, event_type: "NFL Draft", label: "NFL Draft 2021", url: "logos/nfl-draft-2021.gif" },
  { year: 2022, event_type: "NFL Draft", label: "NFL Draft 2022", url: "logos/nfl-draft-2022.gif" },
  { year: 2023, event_type: "NFL Draft", label: "NFL Draft 2023", url: "logos/nfl-draft-2023.gif" },
  { year: 2024, event_type: "NFL Draft", label: "NFL Draft 2024", url: "logos/nfl-draft-2024.gif" },
  { year: 2025, event_type: "NFL Draft", label: "NFL Draft 2025", url: "logos/nfl-draft-2025.gif" },
];
